apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud 
        image: nextcloud
        ports:
        - containerPort: 80
        #env:
        #- name: REDIS_HOST
          #value: redis # i have added redis

        - name: MYSQL_HOST
          value: mariadb
          
        - name: MYSQL_DATABASE
          value: nextcloud 

        - name: MYSQL_USER
          value: nextcloud

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_PASSWORD



        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-storage
          readOnly: false
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc
